import { Application, Context, Converter, DeclarationReflection, ReflectionKind, Comment } from 'typedoc';
import * as fs from 'fs';
import * as path from 'path';

interface TestStatus {
  status: 'pass' | 'fail' | 'skip';
  testName: string;
  duration: number;
}

// This is the main entry point for the TypeDoc plugin.
export function load(app: Application) {
  const testStatusPath = path.join(process.cwd(), '.test-status.json');
  let testStatusMap: any = {};

  // Read the test status file generated by our custom Jest reporter.
  if (fs.existsSync(testStatusPath)) {
    try {
      testStatusMap = JSON.parse(fs.readFileSync(testStatusPath, 'utf-8'));
    } catch (e) {
      console.error("Error reading .test-status.json", e);
    }
  }

  // Listen for the event when TypeDoc creates a declaration (e.g., for a method).
  app.converter.on(Converter.EVENT_CREATE_DECLARATION, (context: Context, reflection: DeclarationReflection) => {
    // We only care about methods within classes.
    if (reflection.kind === ReflectionKind.Method && reflection.parent?.kind === ReflectionKind.Class) {
      const className = reflection.parent.name;
      const methodName = reflection.name;

      const testStatus = testStatusMap[className]?.[methodName];

      if (testStatus) {
        const badge = generateBadge(testStatus);

        // Ensure the comment object exists.
        if (!reflection.comment) {
          reflection.comment = new Comment();
        }

        // Prepend the badge to the method's summary.
        reflection.comment.summary.unshift({
          kind: 'text',
          text: badge,
        });
      }
    }
  });

  // We need to inject some CSS to style our badges.
  // This is a bit of a hack, but it's the most reliable way for a simple plugin.
  app.renderer.on('endPage', (page) => {
    const css = `
      .test-badge {
        display: inline-block;
        padding: 2px 8px;
        border-radius: 4px;
        font-size: 0.8em;
        font-weight: 600;
        margin-right: 10px;
        vertical-align: middle;
        white-space: nowrap;
      }
      .test-pass { background-color: #28a745; color: white; }
      .test-fail { background-color: #dc3545; color: white; }
      .test-skip { background-color: #6c757d; color: white; }
    `;
    if (page.contents) {
      page.contents = page.contents.replace('</head>', `<style>${css}</style></head>`);
    }
  });
}

function generateBadge(testStatus: TestStatus): string {
  const icons = {
    pass: '✓',
    fail: '✗',
    skip: '○',
  };

  const icon = icons[testStatus.status];
  const className = `test-${testStatus.status}`;
  const title = `Test: ${testStatus.testName}\nStatus: ${testStatus.status}\nDuration: ${testStatus.duration}ms`;

  return `<span class="test-badge ${className}" title="${title}">${icon} Tested</span>`;
}
